name: Deploy Extension

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetching tags
        run: git fetch --tags -f || true

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          package-manager-cache: false

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Generate Changelog
        id: generate_changelog
        run: |
          changelog=$(npm run changelog:last --silent)
          {
            echo "changelog<<EOF"
            echo "${changelog}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Package extension
        run: npm run package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: clipboard-manager.vsix

      - name: Publish in marketplace
        run: npx @vscode/vsce publish -p "$VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Publish in Open VSX Registry
        run: npx ovsx publish clipboard-manager.vsix -p "$OVSX_TOKEN"
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
